# Generated by Django 4.1.7 on 2023-04-16 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('total_payment', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
            ],
            options={
                'db_table': 'order',
                'ordering': ['customer_id', '-create_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=200)),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.order')),
            ],
            options={
                'db_table': 'order_item',
                'ordering': ['product'],
            },
        ),
    ]
