# Generated by Django 4.1.7 on 2023-04-15 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(default='', help_text='Unique value for product page URL, created from name', unique=True)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'category',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(default='', help_text='Unique value for product page URL, created from name.', max_length=255, unique=True)),
                ('image', models.CharField(max_length=500, null=True)),
                ('description', models.TextField()),
                ('urlService', models.CharField(max_length=255, null=True)),
                ('categories', models.ManyToManyField(to='product_model.category')),
            ],
            options={
                'db_table': 'product',
                'ordering': ['name'],
            },
        ),
    ]
