# Generated by Django 4.1.7 on 2023-04-15 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_model', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='urlService',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
